#### 1. Create a numpy array with filling random values, and shape of array should be (12,5), and pass this array from a user-defined function, and function should be able to return average, minimum, maximum, and no. of evens in your last row. 
For e.g. consider this is last row [41,52,63,96,85], 
Output:
Average -> 67.4
Minimum -> 41
Maximum -> 96
No. of evens -> 2

In [14]:
import numpy as npy

def my_numpy():
    ary= npy.random.randint(1,101,size=(12,5))                              # an array of ranmdom elements created between no. 1 and 101 with size 12 rows and 5 columns
    print(ary)
    print()
    last_row = ary[-1]                                                      # accessing last row of array
    avg = npy.mean(last_row)                                                # Average finding
    print("Average of the last row= ",avg)
    print()
    min_value= npy.min(last_row)                                            # Finding minimum value in the last row of array
    print("Minimum value in the last row of array= ",min_value)
    print()
    max_value= npy.max(last_row)                                            # Finding maximum value in the last row of array
    print("Maximum value in the last row of given array= ",max_value)
    print()
    no_even= npy.sum(last_row % 2 == 0)                                     # Finding number of even numbers in the last row of array
    print("No. of even numbers in the last row is=",no_even)
    
my_numpy()

[[ 91  64  58  82  19]
 [ 60  78  54  98  92]
 [100  84  12  43  61]
 [ 64  44  66  42  83]
 [ 51  70  45   9  83]
 [ 74  40  32  93  26]
 [ 99   5  84  36  31]
 [ 44  58  24  74  70]
 [ 21   3  98  45  60]
 [ 14  69  24   2  82]
 [ 85  23  85  50   3]
 [ 19  66  85  50  34]]

 Average of the last row=  50.8

Minimum value in the last row of array=  19

Maximum value in the last row of given array=  85

No. of even numbers in the last row is= 3


#### 2. Let’s consider we have an array, e.g.
[[1 2 3 ],
[4 5 6 ],
[7 8 9 ]] 
And apply slicing techniques to get reversed order elements of all the rows, 
like this -> [[3 2 1],
 [6 5 4],
 [9 8 7]

In [19]:
import numpy as np
ary= np.array([[3,4,1],[5,7,9],[1,4,2]])                        # An array constructed
print(ary) 
print()
reverse_array = ary[:, ::-1]                                     # Reversing the array ( [:, ::-1] means "take all rows (:) and reverse the order of elements (::-1) within each row".)
print("array after reversing is = ","\n",reverse_array)

[[3 4 1]
 [5 7 9]
 [1 4 2]]

array after reversing is =  
 [[1 4 3]
 [9 7 5]
 [2 4 1]]
