# NUMPY

### Why use Numpy ?

* Numpy provides efficient storage.

* It also provides better ways of understanding.

* It is fast.

* It is easy to learn.

* Numpy uses relatively less memory to store data.

### construction of array by the help of numpy

In [119]:
import numpy as np 
myarr= np.array([3,56,34,8,9])
myarr

array([ 3, 56, 34,  8,  9])

### Defining the datatype or memory space of the array using Numpy

In [120]:
import numpy as np 
myarr= np.array([3,56,34,9], np.int8)        # Memory defined as 8 bit integer type, if any element size in the given list is more then the given space then it takes any default value.
myarr

array([ 3, 56, 34,  9], dtype=int8)

### Accessing the element of 2D array 

* We can access the element of an array in numpy but for that we have to make our array as 2D array by adding two square brackets in a list then for accessing we have to define row and column dusing accessing.

In [121]:
import numpy as np 
myarr= np.array([[3,56,34,9]], np.int8)        # 2D array in two square brackets
myarr[0,3]                                     # Here 0 = row and 3 = column

9

### Accessing the element of an normal Array

In [122]:
import numpy as np 
myarr= np.array([3,56,34,9], np.int8)        
myarr[0]                                  

3

### Finding shape of an array

In [123]:
import numpy as np 
myarr= np.array([3,56,34,9], np.int8)        
myarr.shape                         

# in output it shows (4,) which means 4 elements is present in a line.       

(4,)

### Finding shape of an 2D array

In [124]:
import numpy as np 
myarr= np.array([[3,56,34,9]], np.int8)        
myarr.shape

# in output it shows (1,4) which means our array has one row and 4 column.

(1, 4)

### Finding data type of an array in numpy

In [125]:
import numpy as np 
myarr= np.array([[3,56,34,9]], np.int8)        
myarr.dtype

dtype('int8')

### Changing element in an array

In [126]:
import numpy as np 
myarr= np.array([[3,56,34,9]], np.int8)        
myarr[0,1]=45
myarr

array([[ 3, 45, 34,  9]], dtype=int8)

### Array Creation Methods In Numpy

#### There are 6 general mechanisms for creating arrays:

1. Conversion from other Python structures (i.e. lists and tuples)

2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

3. Replicating, joining, or mutating existing arrays

4. Reading arrays from disk, either from standard or custom formats

5. Creating arrays from raw bytes through the use of strings or buffers

6. Use of special library functions (e.g., random)

### 1. Conversion from other Python structures

In [127]:
listarray= np.array([[1,2,3], [5,4,6], [0,3,1]])
listarray

array([[1, 2, 3],
       [5, 4, 6],
       [0, 3, 1]])

In [128]:
listarray.shape

(3, 3)

In [129]:
listarray.dtype

dtype('int32')

In [130]:
listarray.size

9

* Data type object constructiom

In [131]:
np.array({34,67,65})      # Here we uses set we can also take dictionary as well

array({65, 34, 67}, dtype=object)

### 2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

* Numpy provides some functions to construct array 

##### 1. Zero function

In [132]:
# we have already taken numpy as np 

zeros= np.zeros((2,5))                      # 2 = no. of rows  5 = no. of columns
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [133]:
zeros.shape

(2, 5)

In [134]:
zeros.dtype

dtype('float64')

#### 2. a_range function

* a_range function provides us numpy array.

In [135]:
rng= np.arange(15)                       
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 3. linspace function

* It provides us equally linearly spaced elements which we define

In [136]:
lspace= np.linspace(1,5,12)                 # 1 = first element, 5 = last element, 12 = space
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

#### 4. empty function 

* This function provides us the array of random elements according to our requirements.

In [137]:
emp= np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.11261095e-306, 1.89146896e-307, 7.56571288e-307],
       [4.00544531e-307, 1.11261095e-306, 3.56043054e-307,
        1.37961641e-306, 2.22518251e-306, 1.33511969e-306],
       [6.23037657e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 3.56036603e-307, 1.37961641e-306],
       [1.37961302e-306, 1.11259940e-306, 1.60219035e-306,
        1.11261570e-306, 1.06811354e-306, 8.34448533e-308]])

##### 4.1. empty_like function

* It copies the size of any previous array and makes an empty array of that size.

In [138]:
emp_like= np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

#### 5. identity function

* It provides us an identity matrix.

In [139]:
ide= np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [140]:
ide.shape

(45, 45)

#### 6. reshape function

* By the help of this function we can reshape any array.

In [141]:
arr= np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [142]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

#### 7. ravel function

* It is used to convert an 2D array in a normal array.

In [143]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [144]:
arr.shape

(99,)

## Numpy Axis

* A NumPy 2D array has two axes we are able to operate over, namely axis 0 and axis 1. Specifying axis 0 allows us to operate over the values vertically, in other words iterating over each row. Axis 1 allows us to operate over the values horizontally, therefore iterating over each column.

In [145]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [146]:
ar.sum(axis=0)     # (1+4+7) (0= row) and 0 axis means sum of that column which intersect that row.

array([12,  8,  9])

#### Attributes and Methods of Numpy

### Attributes

#### 1. Transpose attribute
 
* It converts row into column and column into row

In [147]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

#### 2. flat attribute

* It provides us iterator, means it displays all the items of an array.

In [148]:
ar.flat

In [149]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


#### 3. ndim attribute

* It shows the no. of dimensions of array.

In [150]:
ar.ndim

2

In [151]:
ar.size

9

#### 4. nbytes attribute

* it displays the total storage consume by the elements of the given array.

In [152]:
ar.nbytes

36

### Methods of Numpy

#### 1. argmax method ( 1D Array )

* This method shows the indexing of the maximum element in an array

In [153]:
one= np.array([1,3,4,634,2])
one.argmax()

3

#### 2. argmin method (1D Array )

* This method shows the indexing of the minimum element in an array.

In [154]:
one= np.array([1,3,4,634,2])
one.argmin()

0

#### 3. argsort method

* It provides us the sorted array in the form of their indexing values

In [155]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

#### 4. argmin method ( 2D Array )

In [156]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [157]:
ar.argmin()      # it provides us min. value after converting 2D array into 1D array

# here output is 8 which is the index no. of that 2d array and on 8 indexing value is 0 which is min.

8

#### 4. argmax method ( 2D Array )

In [158]:
ar.argmax()

6

In [159]:
ar.argmax(axis=0)     # axis=0 means it provides the min. value indexing of every column

array([2, 1, 1], dtype=int64)

In [160]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [161]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [162]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [163]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [164]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [165]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [166]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

#### 5. tolist method

* It returns list of numpy array.

In [183]:
ar.tolist()

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

### Sum of two 2D array 

In [167]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [168]:
ar2= np.array([[1,2,1], [4,0,6], [8,1,0]])
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [169]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

#### Multiplication of two 2D array

In [170]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

#### Square root of an 2D array ( sqrt )

In [171]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

#### Sum of all elements of 2D array

In [172]:
ar.sum()

29

#### Maximum value in 2D array 

In [173]:
ar.max()

7

#### Min value in 2D array

In [174]:
ar.min()

0

#### Finding the element in a 2D Array

In [175]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [176]:
np.where(ar>5)          # It returns tuple of array

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

#### Finding the no. of non zero elements in an 2D array

In [177]:
np.count_nonzero(ar)

8

#### Finding non zero elements in an 2D array

In [178]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

### Proof of how numpy takes less space :

In [179]:
import sys

In [180]:
py_ar= [0,4,55,2]
np_ar= np.array(py_ar)

In [181]:
sys.getsizeof(1) * len(py_ar)

112

In [182]:
np_ar.itemsize * np_ar.size

16

* These all the topic discussed above are the main topics and parts of numpy library still the methods and attributes are not covered completely but important methods that are almost used in maximum projects are covered above. 

* For complete details of attributes and methods of numpy library click this link = ( https://docs.scipy.org/doc//numpy-1.10.4/reference/arrays.html )